name: General Help
description: Get general support regarding Node.js
body:
  - type: input
    attributes:
      label: Node.js Version
      description: This can be found via the `node -v` command
      placeholder: v0.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: NPM Version
      description: This can be found via the `npm -v` command
      placeholder: v0.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: >-
        This can be found via the `uname -a` command, or via System Information
        on windows
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Subsystem
      description: What area of Node.js are you experiencing touble with?
      multiple: true
      options:
        - assert
        - async_hooks
        - buffer
        - child_process
        - cluster
        - console
        - constants
        - crypto
        - dgram
        - diagnostics_channel
        - dns
        - domain
        - events
        - fs
        - http
        - http2
        - https
        - inspector
        - path
        - perf_hooks
        - process
        - punycode
        - querystring
        - readline
        - repl
        - stream
        - string_decoder
        - timers
        - tls
        - trace_events
        - tty
        - url
        - util
        - v8
        - vm
        - wasi
        - worker_threads
        - zlib
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproduction
      description: provide steps to reproduce the problem
  - type: textarea
    attributes:
      label: Output
      description: provide the error/output to show the issue
  - type: checkboxes
    attributes:
      label: Before You Submit
      options:
        - label: I have looked for issues that already exist before submitting this
          required: true
        - label: >-
            My issue follows the guidelines in the README file, and follows the
            'How to ask a good question' guide at
            https://stackoverflow.com/help/how-to-ask
          required: true
